# HomeSystem Konfiguration

# Datenbank Daten
Database:
  Host: 'Host'
  Port: 3306
  Database: 'Database'
  Username: 'Username'
  Password: 'Password'
  MaximumConnectionPoolSize: 2

# Generelle Konfiguration
General:
  Prefix: '<color:#00EAF0><bold>HOMES</bold> <white>• <reset>'
  SenderIsConsole: 'Du musst ein Spieler sein, um diesen Befehl zu verwenden.'

# Inventar Konfiguration
Inventory:
  Title: '<white>• <color:#00EAF0><bold>HOMES</bold> <white>•'