name: HomeSystem
main: me.icwj.homesystem.HomeSystem
version: ${project.version}
author: ICodeWithJava
api-version: 1.20
libraries:
  - com.zaxxer:HikariCP:6.3.0

commands:
  Home:
    aliases: [homes, sethome, delhome, zuhause]
    description: Setze, lösche oder teleportiere dich zu deinem Zuhause.